"""Deterministic Champions snow-team policy layers through B4.

B1 provides public-information state, configuration, actions and traces. B2 adds
format-aware static mechanics generated by Pokemon Showdown. B3 reconstructs
public temporal knowledge from the supplied history. B4 adds baseline threat
profiles plus dynamic win-condition/resource valuation. The package still does
not provide a ``choose_action`` implementation.
"""

from .actions import CanonicalLegalAction, canonicalize_legal_action, canonicalize_legal_actions
from .config import PolicyConfig, default_config
from .features import FEATURE_REGISTRY, FeatureDefinition, FeatureFamily
from .mechanics import (
	CHAMPIONS_FORMAT,
	EffectMechanics,
	FormatMechanics,
	ItemMechanics,
	MechanicsSnapshot,
	MoveMechanics,
	SpeciesMechanics,
	UnresolvedMechanicError,
)
from .reconstruction import (
	FakeOutEligibility,
	KnowledgeState,
	TimedConditionKnowledge,
	WeatherObservation,
	build_knowledge_state,
)
from .strategy import (
	DEFAULT_HP_UTILITY_CURVE,
	PlanAssessment,
	PlanLabel,
	ResourceValue,
	RuntimeStrategyAssessment,
	assess_runtime_strategy,
	hp_utility,
)
from .threats import (
	BaselineMoveThreat,
	DamageBand,
	KOConfidence,
	SlotThreat,
	TargetThreat,
	ThreatCategory,
	ThreatModel,
	build_threat_model,
)
from .trace import DecisionTrace

__all__ = [
	"BaselineMoveThreat",
	"CHAMPIONS_FORMAT",
	"CanonicalLegalAction",
	"DEFAULT_HP_UTILITY_CURVE",
	"DamageBand",
	"DecisionTrace",
	"EffectMechanics",
	"FEATURE_REGISTRY",
	"FakeOutEligibility",
	"FeatureDefinition",
	"FeatureFamily",
	"FormatMechanics",
	"ItemMechanics",
	"KOConfidence",
	"KnowledgeState",
	"MechanicsSnapshot",
	"MoveMechanics",
	"PlanAssessment",
	"PlanLabel",
	"PolicyConfig",
	"ResourceValue",
	"RuntimeStrategyAssessment",
	"SlotThreat",
	"SpeciesMechanics",
	"TargetThreat",
	"ThreatCategory",
	"ThreatModel",
	"TimedConditionKnowledge",
	"UnresolvedMechanicError",
	"WeatherObservation",
	"assess_runtime_strategy",
	"build_knowledge_state",
	"build_threat_model",
	"canonicalize_legal_action",
	"canonicalize_legal_actions",
	"default_config",
	"hp_utility",
]
