"""Foundations and static mechanics for the deterministic snow-team policy.

B1 provides public-information state, configuration, actions and traces. B2 adds
format-aware static mechanics generated by Pokemon Showdown. The package still
does not provide a ``choose_action`` implementation.
"""

from .actions import CanonicalLegalAction, canonicalize_legal_action, canonicalize_legal_actions
from .config import PolicyConfig, default_config
from .features import FEATURE_REGISTRY, FeatureDefinition, FeatureFamily
from .knowledge import KnowledgeState, build_knowledge_state
from .mechanics import (
	CHAMPIONS_FORMAT,
	EffectMechanics,
	FormatMechanics,
	ItemMechanics,
	MechanicsSnapshot,
	MoveMechanics,
	SpeciesMechanics,
	UnresolvedMechanicError,
)
from .trace import DecisionTrace

__all__ = [
	"CHAMPIONS_FORMAT",
	"CanonicalLegalAction",
	"DecisionTrace",
	"EffectMechanics",
	"FEATURE_REGISTRY",
	"FeatureDefinition",
	"FeatureFamily",
	"FormatMechanics",
	"ItemMechanics",
	"KnowledgeState",
	"MechanicsSnapshot",
	"MoveMechanics",
	"PolicyConfig",
	"SpeciesMechanics",
	"UnresolvedMechanicError",
	"build_knowledge_state",
	"canonicalize_legal_action",
	"canonicalize_legal_actions",
	"default_config",
]
