"""Foundations, mechanics, and temporal reconstruction for the snow-team policy.

B1 provides public-information state, configuration, actions and traces. B2 adds
format-aware static mechanics generated by Pokemon Showdown. B3 reconstructs
public temporal knowledge from the supplied history. The package still does not
provide a ``choose_action`` implementation.
"""

from .actions import CanonicalLegalAction, canonicalize_legal_action, canonicalize_legal_actions
from .config import PolicyConfig, default_config
from .features import FEATURE_REGISTRY, FeatureDefinition, FeatureFamily
from .mechanics import (
	CHAMPIONS_FORMAT,
	EffectMechanics,
	FormatMechanics,
	ItemMechanics,
	MechanicsSnapshot,
	MoveMechanics,
	SpeciesMechanics,
	UnresolvedMechanicError,
)
from .reconstruction import (
	FakeOutEligibility,
	KnowledgeState,
	TimedConditionKnowledge,
	WeatherObservation,
	build_knowledge_state,
)
from .trace import DecisionTrace

__all__ = [
	"CHAMPIONS_FORMAT",
	"CanonicalLegalAction",
	"DecisionTrace",
	"EffectMechanics",
	"FEATURE_REGISTRY",
	"FakeOutEligibility",
	"FeatureDefinition",
	"FeatureFamily",
	"FormatMechanics",
	"ItemMechanics",
	"KnowledgeState",
	"MechanicsSnapshot",
	"MoveMechanics",
	"PolicyConfig",
	"SpeciesMechanics",
	"TimedConditionKnowledge",
	"UnresolvedMechanicError",
	"WeatherObservation",
	"build_knowledge_state",
	"canonicalize_legal_action",
	"canonicalize_legal_actions",
	"default_config",
]
