"""Format-aware static mechanics consumed by the deterministic Python policy.

The snapshot is generated by tournament/mechanics/champions-snapshot.ts from
``Dex.forFormat``. This module deliberately contains lookup/derivation logic,
not a second battle simulator.
"""

from __future__ import annotations

import hashlib
import json
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Iterable, Mapping

from .serialization import canonical_json


MECHANICS_SNAPSHOT_SCHEMA_VERSION = 1
CHAMPIONS_FORMAT = "gen9championsvgc2026regmb"
SPREAD_TARGETS = frozenset({"allAdjacent", "allAdjacentFoes"})


def to_id(value: str) -> str:
	return "".join(character.lower() for character in value if character.isalnum())


@dataclass(frozen=True)
class FormatMechanics:
	id: str
	name: str
	mod: str
	gen: int
	game_type: str


@dataclass(frozen=True)
class SpeciesMechanics:
	id: str
	name: str
	base_species: str
	forme: str
	types: tuple[str, ...]
	base_stats: tuple[tuple[str, int], ...]
	abilities: tuple[tuple[str, str], ...]
	weight_kg: float
	is_mega: bool
	battle_only: str | tuple[str, ...] | None
	changes_from: str | None
	required_item: str | None
	required_items: tuple[str, ...]
	is_nonstandard: str | None

	@property
	def stats(self) -> dict[str, int]:
		return dict(self.base_stats)


@dataclass(frozen=True)
class MoveMechanics:
	id: str
	name: str
	type: str
	category: str
	base_power: int
	accuracy: int | bool
	pp: int
	priority: int
	target: str
	flags: tuple[str, ...]
	boosts: tuple[tuple[str, int], ...]
	self_boosts: tuple[tuple[str, int], ...]
	status: str | None
	volatile_status: str | None
	side_condition: str | None
	weather: str | None
	terrain: str | None
	pseudo_weather: str | None
	heal: tuple[int, ...] | None
	drain: tuple[int, ...] | None
	recoil: tuple[int, ...] | None
	force_switch: bool
	self_switch: str | bool | None
	breaks_protect: bool
	override_offensive_stat: str | None
	override_defensive_stat: str | None
	ignore_accuracy: bool
	ignore_evasion: bool
	ignore_immunity_json: str
	callback_names: tuple[str, ...]
	is_nonstandard: str | None

	@property
	def ignore_immunity(self) -> bool | dict[str, bool]:
		return json.loads(self.ignore_immunity_json)

	@property
	def is_spread(self) -> bool:
		return self.target in SPREAD_TARGETS


@dataclass(frozen=True)
class EffectMechanics:
	id: str
	name: str
	callback_names: tuple[str, ...]
	is_nonstandard: str | None


@dataclass(frozen=True)
class ItemMechanics(EffectMechanics):
	mega_stone: tuple[tuple[str, str], ...]
	is_berry: bool
	is_choice: bool
	boosts: tuple[tuple[str, int], ...]


class MechanicsSnapshot:
	"""Immutable-indexed view over one generated Showdown mechanics snapshot."""

	def __init__(self, value: Mapping[str, Any], *, verify_hash: bool = True):
		if value.get("schema_version") != MECHANICS_SNAPSHOT_SCHEMA_VERSION:
			raise ValueError(
				f"Unsupported mechanics snapshot schema: {value.get('schema_version')!r}"
			)
		format_value = _mapping(value.get("format"), "format")
		self.format = FormatMechanics(
			id=_string(format_value.get("id"), "format.id"),
			name=_string(format_value.get("name"), "format.name"),
			mod=_string(format_value.get("mod"), "format.mod"),
			gen=_integer(format_value.get("gen"), "format.gen"),
			game_type=_string(format_value.get("game_type"), "format.game_type"),
		)
		self.snapshot_hash = _string(value.get("snapshot_hash"), "snapshot_hash")
		if verify_hash:
			_validate_hash(value, self.snapshot_hash)

		self._type_chart = _parse_type_chart(value.get("type_chart"))
		self._species = _index_unique(
			(_species(_mapping(item, "species item")) for item in _array(value.get("species"), "species")),
			"species",
		)
		self._moves = _index_unique(
			(_move(_mapping(item, "move item")) for item in _array(value.get("moves"), "moves")),
			"moves",
		)
		self._abilities = _index_unique(
			(_effect(_mapping(item, "ability item")) for item in _array(value.get("abilities"), "abilities")),
			"abilities",
		)
		self._items = _index_unique(
			(_item(_mapping(item, "item item")) for item in _array(value.get("items"), "items")),
			"items",
		)
		semantics = _mapping(value.get("semantics"), "semantics")
		if _integer(semantics.get("version"), "semantics.version") != 1:
			raise ValueError("Unsupported semantic mechanics annotation version")
		self._semantics_json = canonical_json(semantics)

	@property
	def semantic_annotations(self) -> dict[str, Any]:
		return json.loads(self._semantics_json)

	@classmethod
	def load(cls, path: str | Path, *, verify_hash: bool = True) -> "MechanicsSnapshot":
		with Path(path).open("r", encoding="utf-8") as handle:
			value = json.load(handle)
		return cls(_mapping(value, "mechanics snapshot"), verify_hash=verify_hash)

	def require_champions_format(self) -> "MechanicsSnapshot":
		if self.format.id != CHAMPIONS_FORMAT or self.format.mod != "champions":
			raise ValueError(
				f"Expected {CHAMPIONS_FORMAT}/champions mechanics, got {self.format.id}/{self.format.mod}"
			)
		return self

	def species(self, value: str) -> SpeciesMechanics:
		return _lookup(self._species, value, "species")

	def move(self, value: str) -> MoveMechanics:
		return _lookup(self._moves, value, "move")

	def ability(self, value: str) -> EffectMechanics:
		return _lookup(self._abilities, value, "ability")

	def item(self, value: str) -> ItemMechanics:
		return _lookup(self._items, value, "item")

	def semantic(self, category: str, value: str) -> dict[str, Any]:
		semantics = self.semantic_annotations
		category_values = semantics.get(category)
		if not isinstance(category_values, Mapping):
			raise KeyError(f"Unknown mechanics semantic category: {category}")
		result = category_values.get(to_id(value), {})
		if not isinstance(result, Mapping):
			raise ValueError(f"Malformed semantic annotation for {category}.{value}")
		return dict(result)

	def type_multiplier(self, attacking_type: str, defending_types: Iterable[str]) -> float:
		attack = _canonical_type(self._type_chart, attacking_type)
		result = 1.0
		seen = False
		for defending_type in defending_types:
			seen = True
			defense = _canonical_type(self._type_chart, defending_type)
			result *= self._type_chart[attack][defense]
		if not seen:
			raise ValueError("At least one defending type is required")
		return result

	def move_multiplier(self, move: str | MoveMechanics, defending_types: Iterable[str]) -> float:
		move_data = self.move(move) if isinstance(move, str) else move
		overrides = self.semantic("moves", move_data.id).get("effectiveness_override", {})
		if not isinstance(overrides, Mapping):
			raise ValueError(f"Malformed effectiveness override for {move_data.id}")
		attack = _canonical_type(self._type_chart, move_data.type)
		result = 1.0
		seen = False
		for defending_type in defending_types:
			seen = True
			defense = _canonical_type(self._type_chart, defending_type)
			if defense in overrides:
				multiplier = float(overrides[defense])
			else:
				multiplier = self._type_chart[attack][defense]
			result *= multiplier
		if not seen:
			raise ValueError("At least one defending type is required")
		return result

	def is_immune(self, move_or_type: str, defending_types: Iterable[str], *, move: bool = True) -> bool:
		multiplier = self.move_multiplier(move_or_type, defending_types) if move else self.type_multiplier(
			move_or_type, defending_types
		)
		return multiplier == 0

	def wide_guard_blocks(self, move: str | MoveMechanics) -> bool:
		move_data = self.move(move) if isinstance(move, str) else move
		return move_data.target in SPREAD_TARGETS and not move_data.breaks_protect

	def weather_grants_perfect_accuracy(self, move: str | MoveMechanics, weather: str | None) -> bool:
		if not weather:
			return False
		move_data = self.move(move) if isinstance(move, str) else move
		weather_values = self.semantic("moves", move_data.id).get("always_hits_in_weather", [])
		return to_id(weather) in {to_id(str(value)) for value in weather_values}

	def ability_bypasses_accuracy(self, ability: str) -> bool:
		return bool(self.semantic("abilities", ability).get("accuracy_bypass", False))

	def form_after_item_transformation(self, species: str, item: str) -> SpeciesMechanics | None:
		base = self.species(species)
		stone = self.item(item)
		mapping = dict(stone.mega_stone)
		result = mapping.get(base.base_species) or mapping.get(base.name)
		return self.species(result) if result else None


def _validate_hash(value: Mapping[str, Any], supplied_hash: str) -> None:
	if not supplied_hash.startswith("sha256:"):
		raise ValueError("mechanics snapshot hash must use sha256")
	payload = dict(value)
	payload.pop("snapshot_hash", None)
	expected = "sha256:" + hashlib.sha256(canonical_json(payload).encode("utf-8")).hexdigest()
	if supplied_hash != expected:
		raise ValueError(f"Mechanics snapshot hash mismatch: expected {expected}, got {supplied_hash}")


def _parse_type_chart(value: Any) -> dict[str, dict[str, float]]:
	chart = _mapping(value, "type_chart")
	result: dict[str, dict[str, float]] = {}
	for attack, row_value in chart.items():
		row = _mapping(row_value, f"type_chart.{attack}")
		result[str(attack)] = {}
		for defense, multiplier in row.items():
			if isinstance(multiplier, bool) or not isinstance(multiplier, (int, float)) or multiplier < 0:
				raise ValueError(f"Invalid type multiplier {attack}->{defense}: {multiplier!r}")
			result[str(attack)][str(defense)] = float(multiplier)
	if not result:
		raise ValueError("type_chart must not be empty")
	return result


def _species(value: Mapping[str, Any]) -> SpeciesMechanics:
	battle_only = value.get("battle_only")
	if isinstance(battle_only, list):
		battle_only_value: str | tuple[str, ...] | None = tuple(str(item) for item in battle_only)
	elif battle_only is None or isinstance(battle_only, str):
		battle_only_value = battle_only
	else:
		raise ValueError("species.battle_only must be a string, array, or null")
	return SpeciesMechanics(
		id=_string(value.get("id"), "species.id"),
		name=_string(value.get("name"), "species.name"),
		base_species=_string(value.get("base_species"), "species.base_species"),
		forme=str(value.get("forme") or ""),
		types=tuple(str(item) for item in _array(value.get("types"), "species.types")),
		base_stats=_number_pairs(value.get("base_stats"), "species.base_stats"),
		abilities=_string_pairs(value.get("abilities"), "species.abilities"),
		weight_kg=float(value.get("weight_kg", 0)),
		is_mega=bool(value.get("is_mega", False)),
		battle_only=battle_only_value,
		changes_from=_optional_string(value.get("changes_from"), "species.changes_from"),
		required_item=_optional_string(value.get("required_item"), "species.required_item"),
		required_items=tuple(str(item) for item in _array(value.get("required_items"), "species.required_items")),
		is_nonstandard=_optional_string(value.get("is_nonstandard"), "species.is_nonstandard"),
	)


def _move(value: Mapping[str, Any]) -> MoveMechanics:
	accuracy = value.get("accuracy")
	if accuracy is not True and (isinstance(accuracy, bool) or not isinstance(accuracy, int)):
		raise ValueError("move.accuracy must be true or an integer")
	return MoveMechanics(
		id=_string(value.get("id"), "move.id"), name=_string(value.get("name"), "move.name"),
		type=_string(value.get("type"), "move.type"), category=_string(value.get("category"), "move.category"),
		base_power=_integer(value.get("base_power"), "move.base_power"), accuracy=accuracy,
		pp=_integer(value.get("pp"), "move.pp"), priority=_integer(value.get("priority"), "move.priority"),
		target=_string(value.get("target"), "move.target"),
		flags=tuple(str(item) for item in _array(value.get("flags"), "move.flags")),
		boosts=_number_pairs(value.get("boosts"), "move.boosts"),
		self_boosts=_number_pairs(value.get("self_boosts"), "move.self_boosts"),
		status=_optional_string(value.get("status"), "move.status"),
		volatile_status=_optional_string(value.get("volatile_status"), "move.volatile_status"),
		side_condition=_optional_string(value.get("side_condition"), "move.side_condition"),
		weather=_optional_string(value.get("weather"), "move.weather"),
		terrain=_optional_string(value.get("terrain"), "move.terrain"),
		pseudo_weather=_optional_string(value.get("pseudo_weather"), "move.pseudo_weather"),
		heal=_optional_int_tuple(value.get("heal"), "move.heal"),
		drain=_optional_int_tuple(value.get("drain"), "move.drain"),
		recoil=_optional_int_tuple(value.get("recoil"), "move.recoil"),
		force_switch=bool(value.get("force_switch", False)), self_switch=value.get("self_switch"),
		breaks_protect=bool(value.get("breaks_protect", False)),
		override_offensive_stat=_optional_string(value.get("override_offensive_stat"), "move.override_offensive_stat"),
		override_defensive_stat=_optional_string(value.get("override_defensive_stat"), "move.override_defensive_stat"),
		ignore_accuracy=bool(value.get("ignore_accuracy", False)), ignore_evasion=bool(value.get("ignore_evasion", False)),
		ignore_immunity_json=canonical_json(value.get("ignore_immunity", False)),
		callback_names=tuple(str(item) for item in _array(value.get("callback_names"), "move.callback_names")),
		is_nonstandard=_optional_string(value.get("is_nonstandard"), "move.is_nonstandard"),
	)


def _effect(value: Mapping[str, Any]) -> EffectMechanics:
	return EffectMechanics(
		id=_string(value.get("id"), "effect.id"), name=_string(value.get("name"), "effect.name"),
		callback_names=tuple(str(item) for item in _array(value.get("callback_names"), "effect.callback_names")),
		is_nonstandard=_optional_string(value.get("is_nonstandard"), "effect.is_nonstandard"),
	)


def _item(value: Mapping[str, Any]) -> ItemMechanics:
	base = _effect(value)
	mega_stone_value = value.get("mega_stone")
	mega_stone = () if mega_stone_value is None else _string_pairs(mega_stone_value, "item.mega_stone")
	return ItemMechanics(
		base.id, base.name, base.callback_names, base.is_nonstandard, mega_stone,
		bool(value.get("is_berry", False)), bool(value.get("is_choice", False)),
		_number_pairs(value.get("boosts"), "item.boosts"),
	)


def _index_unique(values: Iterable[Any], label: str) -> dict[str, Any]:
	result = {}
	for value in values:
		if value.id in result:
			raise ValueError(f"Duplicate {label} id: {value.id}")
		result[value.id] = value
	return result


def _lookup(values: Mapping[str, Any], value: str, label: str) -> Any:
	key = to_id(value)
	try:
		return values[key]
	except KeyError as error:
		raise KeyError(f"Unknown {label}: {value}") from error


def _canonical_type(chart: Mapping[str, Any], value: str) -> str:
	wanted = to_id(value)
	for type_name in chart:
		if to_id(type_name) == wanted:
			return type_name
	raise KeyError(f"Unknown type: {value}")


def _mapping(value: Any, label: str) -> Mapping[str, Any]:
	if not isinstance(value, Mapping):
		raise ValueError(f"{label} must be an object")
	return value


def _array(value: Any, label: str) -> list[Any]:
	if not isinstance(value, list):
		raise ValueError(f"{label} must be an array")
	return value


def _string(value: Any, label: str) -> str:
	if not isinstance(value, str) or not value:
		raise ValueError(f"{label} must be a non-empty string")
	return value


def _optional_string(value: Any, label: str) -> str | None:
	if value is None:
		return None
	if not isinstance(value, str):
		raise ValueError(f"{label} must be a string or null")
	return value


def _integer(value: Any, label: str) -> int:
	if isinstance(value, bool) or not isinstance(value, int):
		raise ValueError(f"{label} must be an integer")
	return value


def _number_pairs(value: Any, label: str) -> tuple[tuple[str, int], ...]:
	mapping = _mapping(value, label)
	pairs = []
	for key, item in sorted(mapping.items()):
		pairs.append((str(key), _integer(item, f"{label}.{key}")))
	return tuple(pairs)


def _string_pairs(value: Any, label: str) -> tuple[tuple[str, str], ...]:
	mapping = _mapping(value, label)
	return tuple(sorted((str(key), str(item)) for key, item in mapping.items()))


def _optional_int_tuple(value: Any, label: str) -> tuple[int, ...] | None:
	if value is None:
		return None
	return tuple(_integer(item, label) for item in _array(value, label))
